# Generated by Django 5.0.6 on 2024-06-21 15:01

import django.core.validators
import django.db.models.deletion
import serviceproviders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=80, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=serviceproviders.models.service_provider_img_path)),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('website', models.URLField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('account_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'indexes': [models.Index(fields=['id', 'account_creator', 'image'], name='serviceprov_id_cfe6c8_idx')],
            },
        ),
    ]
