# Generated by Django 4.2.11 on 2024-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0002_serviceprovider_documentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='show_connections',
            field=models.BooleanField(default=False),
        ),
    ]
