# Generated by Django 5.0.6 on 2024-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0003_serviceprovider_show_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='show_connections',
            field=models.BooleanField(default=True),
        ),
    ]
