# Generated by Django 5.0.6 on 2024-09-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0005_serviceprovider_certified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='certification_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('oauth', 'OAuth')], max_length=20, null=True),
        ),
    ]
