# Generated by Django 4.2.11 on 2024-03-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0036_alter_researcher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
