# Generated by Django 4.2.11 on 2024-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researchers", "0037_researcher_is_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcher",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
