# Generated by Django 4.2.11 on 2024-05-28 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("researchers", "0038_researcher_is_submitted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researcher",
            name="is_submitted",
        ),
    ]
