# Generated by Django 3.1.14 on 2023-11-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0045_auto_20220909_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='boundary_name',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='boundary_source',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.ManyToManyField(related_name='coordinates', to='communities.Coordinate')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='boundaries',
            field=models.ManyToManyField(related_name='boundaries', to='communities.Boundary'),
        ),
    ]
