# Generated by Django 3.1.14 on 2023-12-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0046_auto_20231127_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='native_land_slug',
        ),
        migrations.AlterField(
            model_name='community',
            name='name_of_boundaries',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='source_of_boundaries',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
