# Generated by Django 3.2 on 2024-01-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0046_auto_20231220_1706'),
        ('communities', '0047_auto_20240103_2222'),
    ]

    operations = [
    ]
