# Generated by Django 3.1.14 on 2023-11-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0047_auto_20231125_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='boundary_name',
            new_name='name_of_boundaries',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='boundary_source',
            new_name='source_of_boundaries',
        ),
    ]
