# Generated by Django 3.1.14 on 2023-12-11 03:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0047_auto_20231211_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundary',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='boundary',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True), blank=True, null=True, size=2), blank=True, null=True, size=None),
        ),
    ]
