# Generated by Django 3.1.14 on 2024-01-23 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0047_auto_20240103_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='name_of_boundaries',
            new_name='name_of_boundary',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='source_of_boundaries',
            new_name='source_of_boundary',
        ),
        migrations.RemoveField(
            model_name='community',
            name='boundaries',
        ),
        migrations.AddField(
            model_name='community',
            name='boundary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.boundary'),
        ),
    ]
