# Generated by Django 3.2 on 2024-01-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0048_merge_0046_auto_20231220_1706_0047_auto_20240103_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
