# Generated by Django 3.2 on 2024-01-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0048_auto_20240123_0046'),
        ('communities', '0049_alter_boundary_id'),
    ]

    operations = [
    ]
