# Generated by Django 4.2 on 2024-03-20 19:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0050_merge_0048_auto_20240123_0046_0049_alter_boundary_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundary",
            name="poly",
            field=django.contrib.gis.db.models.fields.PolygonField(
                null=True, srid=4326
            ),
        ),
    ]
