# Generated by Django 4.2.11 on 2024-04-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0050_merge_0048_auto_20240123_0046_0049_alter_boundary_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("", "---------"),
                    ("admin", "admin"),
                    ("editor", "editor"),
                    ("viewer", "viewer"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
