# Generated by Django 4.2.11 on 2024-06-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0050_merge_0048_auto_20240123_0046_0049_alter_boundary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='share_boundary_publicly',
            field=models.BooleanField(default=True),
        ),
    ]
