# Generated by Django 4.2.11 on 2024-10-17 20:08

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0051_community_share_boundary_publicly'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='polygons',
            field=djgeojson.fields.MultiPolygonField(null=True),
        ),
    ]
