# Generated by Django 5.0.6 on 2024-06-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0051_alter_invitemember_role'),
        ('communities', '0051_community_share_boundary_publicly'),
    ]

    operations = [
    ]
