# Generated by Django 5.0.6 on 2024-07-09 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0052_merge_20240613_1240'),
        ('institutions', '0035_remove_institution_is_submitted'),
        ('serviceproviders', '0002_serviceprovider_documentation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invitemember',
            name='communities_sender__b17605_idx',
        ),
        migrations.AddField(
            model_name='invitemember',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_invitation', to='serviceproviders.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='invitemember',
            index=models.Index(fields=['sender', 'receiver', 'community', 'institution', 'service_provider'], name='communities_sender__ff1b4a_idx'),
        ),
    ]
