# Generated by Django 5.0.6 on 2024-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0053_remove_invitemember_communities_sender__b17605_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='show_sp_connection',
            field=models.BooleanField(default=True),
        ),
    ]
