# Generated by Django 5.0.6 on 2024-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0054_community_show_sp_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='sp_privacy',
            field=models.CharField(choices=[('public', 'Public/Contributor'), ('all', 'All')], default='all', max_length=20),
        ),
    ]
