# Generated by Django 5.0.9 on 2024-10-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0055_community_sp_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
