# Generated by Django 4.2.11 on 2024-10-20 16:20

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0056_community_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='geometry',
            field=djgeojson.fields.MultiPolygonField(null=True),
        ),
    ]
