# Generated by Django 3.1.14 on 2023-11-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0181_auto_20231124_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Contributor', 'Contributor'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
