# Generated by Django 3.1.14 on 2024-01-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0181_auto_20240103_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Contributor', 'Contributor')], max_length=20, null=True),
        ),
    ]
