# Generated by Django 3.1.14 on 2023-11-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0182_auto_20231125_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Contributor', 'Contributor')], max_length=20, null=True),
        ),
    ]
