# Generated by Django 3.2 on 2024-01-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0183_auto_20240103_2222'),
        ('projects', '0188_alter_project_project_privacy'),
    ]

    operations = [
    ]
