# Generated by Django 3.2 on 2024-01-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0184_auto_20240123_0046'),
        ('projects', '0189_merge_20240118_1752'),
    ]

    operations = [
    ]
