# Generated by Django 3.2 on 2024-02-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0181_auto_20231115_0256'),
        ('projects', '0190_merge_20240126_2126'),
    ]

    operations = [
    ]
