# Generated by Django 3.2 on 2024-04-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0191_alter_project_project_privacy'),
        ('projects', '0191_alter_project_project_privacy_and_more'),
    ]

    operations = [
    ]
