# Generated by Django 4.2.11 on 2024-05-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0191_alter_project_project_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(blank=True, db_index=True, to='projects.project', verbose_name='Related Projects'),
        ),
    ]
