# Generated by Django 3.2 on 2024-02-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0191_merge_20240214_1931'),
        ('projects', '0191_merge_20240214_1946'),
    ]

    operations = [
    ]
