# Generated by Django 3.2 on 2024-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0191_alter_project_project_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_projects_project_related_projects_+', to='projects.Project', verbose_name='Related Projects'),
        ),
    ]
