# Generated by Django 4.2.13 on 2024-08-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0192_merge'),
        ('projects', '0192_project_boundary_project_name_of_boundary_and_more'),
    ]

    operations = [
    ]
