# Generated by Django 3.2 on 2024-04-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0192_alter_project_related_projects'),
        ('projects', '0193_alter_project_related_projects'),
    ]

    operations = [
    ]
