# Generated by Django 5.0.6 on 2024-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0194_merge_20240412_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='related_projects', to='projects.project', verbose_name='Related Projects'),
        ),
    ]
