# Generated by Django 4.2.11 on 2024-05-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0195_alter_project_related_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(blank=True, db_index=True, to='projects.project', verbose_name='Related Projects'),
        ),
    ]
