# Generated by Django 5.0.6 on 2024-07-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0192_project_boundary_project_name_of_boundary_and_more'),
        ('projects', '0196_alter_project_related_projects'),
    ]

    operations = [
    ]
