# Generated by Django 4.2.11 on 2024-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0197_project_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_of_boundary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='share_boundary_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_of_boundary',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
