# Generated by Django 5.0.6 on 2024-09-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0193_merge_20240826_1901'),
        ('projects', '0197_merge_20240729_1516'),
    ]

    operations = [
    ]
