steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "setup-envs"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        printf "%s" "$$APP_ENGINE_ENVS" > ./env.sh
        printf "%s" "$$DJANGO_STORAGES_GCS_KEY" > ./django-storages-gcs-key.json
        chmod +x ./env.sh
    secretEnv: ["APP_ENGINE_ENVS", "DJANGO_STORAGES_GCS_KEY"]
    waitFor: ["-"]
  - name: "python:3.8-slim-buster"
    id: "install-deps"
    entrypoint: "python3"
    args: ["-m", "pip", "install", "-r", "requirements.txt", "--user"]
    waitFor: [ "-" ]
  - name: "python:3.8-slim-buster"
    id: "collect-statics"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        source ./env.sh
        python3 ./manage.py collectstatic --noinput
    waitFor: ["setup-envs", "install-deps"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "deploy"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        source ./env.sh
        gcloud app deploy
    waitFor: ["collect-statics"]

#substitutions:
#  _SQL_DB: ""
availableSecrets:
  secretManager:
    - versionName: "projects/local-contexts-hub-sandbox/secrets/APP_ENGINE_ENVS/versions/latest"
      env: "APP_ENGINE_ENVS"
    - versionName: "projects/local-contexts-hub-sandbox/secrets/django-storages-gcs-key/versions/latest"
      env: "DJANGO_STORAGES_GCS_KEY"
