steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "setup-envs"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        printf "%s" "$$APP_ENGINE_ENVS" > ./env.sh
        printf "%s" "$$DJANGO_STORAGES_GCS_KEY" > ./django-storages-gcs-key.json
        chmod +x ./env.sh
    secretEnv: ["APP_ENGINE_ENVS", "DJANGO_STORAGES_GCS_KEY"]
    waitFor: ["-"]

  - name: "python:3.8-slim-buster"
    id: "install-deps"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        python3 -m pip install -r requirements.txt --user
        apt -y update
        apt -y install postgresql-client
    waitFor: [ "-" ]

  - name: "python:3.8-slim-buster"
    id: "collect-statics"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        source ./env.sh
        python3 ./manage.py collectstatic --noinput
    waitFor: ["setup-envs", "install-deps"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "deploy"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        source ./env.sh
        gcloud app deploy
    waitFor: ["collect-statics"]

  - name: "gcr.io/cloud-builders/wget"
    id: "install-proxy"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        wget -O /workspace/cloud_sql_proxy \
          "https://storage.googleapis.com/cloudsql-proxy/v1.19.1/cloud_sql_proxy.linux.386" \
          && chmod +x /workspace/cloud_sql_proxy
    waitFor: ["-"]

  - name: "python:3.8-slim-buster"
    id: "migrate-db"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        source ./env.sh
        export DB_HOST=$$DB_SQL_PROXY
        /workspace/cloud_sql_proxy -dir=/workspace -instances=$$DB_CONNECTION_NAME \
          & sleep 2 \
          && python3 ./manage.py makemigrations \
          && python3 ./manage.py migrate
    waitFor: ["setup-envs", "install-deps", "install-proxy", "deploy"]

availableSecrets:
  secretManager:
    - versionName: "projects/local-context-hub-staging/secrets/APP_ENGINE_ENVS/versions/latest"
      env: "APP_ENGINE_ENVS"
    - versionName: "projects/local-context-hub-staging/secrets/django-storages-gcs-key/versions/latest"
      env: "DJANGO_STORAGES_GCS_KEY"
