[tool.coverage.run]
omit = [
    '*/migrations/*',
    '*/apps.py',
    'tests/*',
    'manage.py'
]

[tool.yapfignore]
ignore_patterns = [
    '*/apps.py',
    'localcontexts/settings.py',
    '*/migrations/*',
    'tests/*',
    'manage.py'
]

[tool.isort]
skip_glob = [
    '*/apps.py',
    'localcontexts/settings.py',
    '*/migrations/*',
    'tests/*',
    'manage.py'
]