[tool.coverage.run]
omit = [
    '*/migrations/*',
    '*/apps.py',
    'tests/*',
    'manage.py'
]

[tool.yapfignore]
column_limit=79
ignore_patterns = [
    '*/apps.py',
    'localcontexts/settings.py',
    '*/migrations/*',
    'tests/*',
    'manage.py'
]
