# Generated by Django 3.2 on 2023-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bclabels', '0053_auto_20230727_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bclabel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
