# Generated by Django 4.2 on 2024-03-20 1:32

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("helpers", "0060_auto_20231220_1706"),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
