# Generated by Django 5.0.6 on 2024-06-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0060_auto_20231220_1706'),
        ('institutions', '0035_remove_institution_is_submitted'),
        ('researchers', '0039_remove_researcher_is_submitted'),
        ('serviceproviders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='opentocollaboratenoticeurl',
            name='helpers_ope_institu_f0c7a8_idx',
        ),
        migrations.AddField(
            model_name='opentocollaboratenoticeurl',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otc_service_provider_url', to='serviceproviders.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='opentocollaboratenoticeurl',
            index=models.Index(fields=['institution', 'researcher', 'service_provider'], name='helpers_ope_institu_d9d192_idx'),
        ),
    ]
