# Generated by Django 5.0.6 on 2024-06-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0061_remove_opentocollaboratenoticeurl_helpers_ope_institu_f0c7a8_idx_and_more'),
        ('serviceproviders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticedownloadtracker',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.serviceprovider'),
        ),
    ]
