# Generated by Django 4.2.11 on 2024-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0063_hubactivity_service_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubactivity',
            name='action_type',
            field=models.CharField(choices=[('New Member Added', 'New Member Added'), ('New User', 'New User'), ('New Researcher', 'New Researcher'), ('New Community', 'New Community'), ('New Institution', 'New Institution'), ('New Service Provider', 'New Service Provider'), ('Project Edited', 'Project Edited'), ('Project Created', 'Project Created'), ('Community Notified', 'Community Notified'), ('Label(s) Applied', 'Label(s) Applied'), ('Disclosure Notice(s) Added', 'Disclosure Notice(s) Added'), ('Engagement Notice Added', 'Engagement Notice Added')], max_length=30, null=True),
        ),
    ]
