# Generated by Django 3.2 on 2024-04-09 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0050_merge_0048_auto_20240123_0046_0049_alter_boundary_id'),
        ('institutions', '0032_institution_is_subscribed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchers', '0036_alter_researcher_id'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountapikey',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='accountapikey',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='accountapikey',
            name='institutions',
        ),
        migrations.AddField(
            model_name='accountapikey',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_api_keys', to='communities.community'),
        ),
        migrations.AddField(
            model_name='accountapikey',
            name='developer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountapikey',
            name='encrypted_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accountapikey',
            name='institution',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_api_keys', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='accountapikey',
            name='researcher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_api_keys', to='researchers.researcher'),
        ),
    ]
