# Generated by Django 3.2 on 2024-04-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_accountapikey_encrypted_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapikey',
            name='encrypted_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
