# Generated by Django 3.2 on 2024-03-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0050_merge_0048_auto_20240123_0046_0049_alter_boundary_id'),
        ('institutions', '0031_alter_institution_id'),
        ('researchers', '0036_alter_researcher_id'),
        ('accounts', '0019_auto_20231220_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_count', models.IntegerField()),
                ('api_key_count', models.IntegerField()),
                ('project_count', models.IntegerField()),
                ('notification_count', models.IntegerField()),
                ('is_subscribed', models.BooleanField(default=False)),
                ('community', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_community', to='communities.community')),
                ('institution', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_institution', to='institutions.institution')),
                ('researcher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_researcher', to='researchers.researcher')),
            ],
        ),
    ]
