# Generated by Django 4.2.11 on 2024-03-22 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0021_subscription_date_last_updated_subscription_end_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_subscribed",
        ),
    ]
