# Generated by Django 3.2 on 2024-04-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0032_institution_is_subscribed'),
        ('researchers', '0036_alter_researcher_id'),
        ('communities', '0050_merge_0048_auto_20240123_0046_0049_alter_boundary_id'),
        ('accounts', '0022_remove_subscription_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='api_key_count',
            field=models.IntegerField(help_text='For unlimited counts the value shoud be -1'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='community',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_community', to='communities.community'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_institution', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notification_count',
            field=models.IntegerField(help_text='For unlimited counts the value shoud be -1'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='project_count',
            field=models.IntegerField(help_text='For unlimited counts the value shoud be -1'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='researcher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_researcher', to='researchers.researcher'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='users_count',
            field=models.IntegerField(help_text='For unlimited counts the value shoud be -1'),
        ),
    ]
