# Generated by Django 3.2 on 2024-04-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_subscription_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='api_key_count',
            field=models.IntegerField(help_text='For unlimited counts the value shoud be -1'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notification_count',
            field=models.IntegerField(help_text='For unlimited counts the value shoud be -1'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='project_count',
            field=models.IntegerField(help_text='For unlimited counts the value shoud be -1'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='users_count',
            field=models.IntegerField(help_text='For unlimited counts the value shoud be -1'),
        ),
    ]
