# Generated by Django 3.2 on 2024-04-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20240408_1250'),
        ('accounts', '0023_auto_20240411_1850'),
    ]

    operations = [
    ]
