# Generated by Django 4.2 on 2024-05-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_inactiveuser"),
        ("accounts", "0024_merge_0023_auto_20240408_1250_0023_auto_20240411_1850"),
    ]

    operations = []
