# Generated by Django 5.0.6 on 2024-08-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_subscription_service_provider_and_more'),
        ('communities', '0053_remove_invitemember_communities_sender__b17605_idx_and_more'),
        ('institutions', '0035_remove_institution_is_submitted'),
        ('researchers', '0039_remove_researcher_is_submitted'),
        ('serviceproviders', '0003_serviceprovider_show_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communities', models.ManyToManyField(blank=True, related_name='service_provider_communities', to='communities.community')),
                ('institutions', models.ManyToManyField(blank=True, related_name='service_provider_institutions', to='institutions.institution')),
                ('researchers', models.ManyToManyField(blank=True, related_name='service_provider_researchers', to='researchers.researcher')),
                ('service_provider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_connection', to='serviceproviders.serviceprovider')),
            ],
            options={
                'verbose_name': 'Service Provider Connection',
                'verbose_name_plural': 'Service Provider Connections',
                'indexes': [models.Index(fields=['service_provider'], name='accounts_se_service_533d9c_idx')],
            },
        ),
    ]
