# Generated by Django 5.0.6 on 2024-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_subscription_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('cc_notice_only', 'CC Notice Only'), ('cc_notices', 'CC Notices'), ('member', 'Member'), ('service_provide', 'Service Provider'), ('founding_supporter', 'Founding Supporter')], max_length=20),
        ),
    ]
