# Generated by Django 5.0.9 on 2024-09-18 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_subscription_subscription_type'),
        ('communities', '0055_community_sp_privacy'),
        ('institutions', '0039_alter_institution_sp_privacy'),
        ('researchers', '0041_researcher_sp_privacy'),
        ('serviceproviders', '0005_serviceprovider_certified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_type', models.CharField(choices=[('User', 'User Bundle'), ('API', 'API Bundle'), ('Project', 'Project Bundle'), ('Notification', 'Notification Bundle')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('community', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_bundle', to='communities.community')),
                ('institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_bundle', to='institutions.institution')),
                ('researcher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_bundle', to='researchers.researcher')),
                ('service_provider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_bundle', to='serviceproviders.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
