# Generated by Django 5.0.6 on 2024-09-12 14:09

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_subscription_subscription_type'),
        ('communities', '0054_community_show_sp_connection'),
        ('institutions', '0036_institution_show_sp_connection_and_more'),
        ('researchers', '0040_researcher_show_sp_connection'),
        ('serviceproviders', '0004_alter_serviceprovider_show_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('user_bundle', 'User Bundle'), ('api_bundle', 'API Bundle'), ('project_bundle', 'Project Bundle'), ('notification_bundle', 'Notification Bundle')], max_length=30), blank=True, size=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('community', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_bundle', to='communities.community')),
                ('institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_bundle', to='institutions.institution')),
                ('researcher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_bundle', to='researchers.researcher')),
                ('service_provider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_bundle', to='serviceproviders.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
