# Generated by Django 5.0.6 on 2024-09-12 15:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_bundletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundletype',
            name='bundle_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('User', 'User Bundle'), ('API', 'API Bundle'), ('Project', 'Project Bundle'), ('Notification', 'Notification Bundle')], max_length=30), blank=True, size=4),
        ),
    ]
