# Generated by Django 3.2 on 2023-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0030_auto_20230607_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
