# Generated by Django 3.2 on 2024-03-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0031_alter_institution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
