# Generated by Django 4.2.11 on 2024-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0032_institution_is_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
