# Generated by Django 4.2.11 on 2024-05-03 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0033_institution_is_submitted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="is_approved",
        ),
    ]
