# Generated by Django 5.0.6 on 2024-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0036_institution_show_sp_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sp_privacy',
            field=models.CharField(choices=[('Public', 'Public/Contributor'), ('All', 'All')], default='All', max_length=20),
        ),
    ]
