# Generated by Django 5.0.6 on 2024-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0038_alter_institution_sp_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='sp_privacy',
            field=models.CharField(choices=[('public', 'Public/Contributor'), ('all', 'All')], default='all', max_length=20),
        ),
    ]
