# Generated by Django 5.0.9 on 2024-10-17 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0039_alter_institution_sp_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='sp_privacy',
            field=models.CharField(choices=[('public', 'Public/Contributor'), ('all', 'All')], default='all', max_length=20, null=True),
        ),
    ]
