# Generated by Django 5.0.6 on 2024-07-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0040_auto_20231220_1706'),
        ('serviceproviders', '0002_serviceprovider_documentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.serviceprovider'),
        ),
    ]
