# Generated by Django 5.0.6 on 2024-07-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0041_usernotification_service_provider'),
        ('serviceproviders', '0002_serviceprovider_documentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionnotification',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.serviceprovider'),
        ),
    ]
